server {
    listen 80;
    server_name localhost;
    location /backend/ {
        proxy_pass https://zotsport-backend.onrender.com/;
        proxy_set_header Host zotsport-backend.onrender.com;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_read_timeout 300s;     # ← 5 минут — должно хватить на письмо
        proxy_connect_timeout 300s;
        proxy_send_timeout 300s;
        
        # Отключаем проверку SSL (для самоподписанных сертификатов Render)
        proxy_ssl_verify off;
        proxy_ssl_server_name on;
        
        # Важно для API
        proxy_set_header Accept "application/json";
        proxy_set_header Content-Type "application/json; charset=UTF-8";
        
        # Убираем add_header Content-Type, так как это меняет ответ от бэкенда
        proxy_set_header Accept-Charset "UTF-8";

        add_header Content-Type "text/html; charset=UTF-8";
    }

    location / {
        proxy_pass https://zotsport-frontend.onrender.com/;
        proxy_set_header Host zotsport-frontend.onrender.com;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        
        # Отключаем проверку SSL
        proxy_ssl_verify off;
        proxy_ssl_server_name on;

        add_header Content-Type "text/html; charset=UTF-8";
    }
}