server {
    listen 80;
    server_name localhost;
    location /backend/ {
        proxy_pass http://zotsport-backend:80/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Accept-Charset "UTF-8";
        add_header Content-Type "text/html; charset=UTF-8";
    }

    location / {
        proxy_pass http://zotsport-frontend:80/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Accept-Charset "UTF-8";
        add_header Content-Type "text/html; charset=UTF-8";
    }
}