name: CI/CD
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login Docker Hub
        uses: docker/login-action@v3
        with:
            username: zdima4444
            password: ${{secrets.DOCKER_PASSWORD}}
      - name: Build and push frontend
        uses: docker/build-push-action@v6
        with:
          context: .
          file: frontend/Dockerfile
          push: true
          tags: zdima4444/zotsport-frontend:latest
      - name: Build and push backend
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker-backend/Dockerfile
          push: true
          tags: zdima4444/zotsport-backend:latest
      - name: Build and push sqlite
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker-sqlite/Dockerfile
          push: true
          tags: zdima4444/zotsport-sqlite:latest
      - name: Build and push proxy
        uses: docker/build-push-action@v6
        with:
          context: .
          file: proxy/Dockerfile
          push: true
          tags: zdima4444/zotsport-proxy:latest
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{secrets.SERVER_IP_NEW}}
          username: ${{secrets.SERVER_USER}}
          key: ${{secrets.SSH_KEY}}
          script: |
            cd /root/zotsport/curs3
            export DOCKER_USERNAME=zdima4444
            docker pull zdima4444/zotsport-frontend:latest
            docker pull zdima4444/zotsport-backend:latest
            docker pull zdima4444/zotsport-sqlite:latest
            docker pull zdima4444/zotsport-proxy:latest
            docker stack deploy -c docker-compose.yaml zotsport
